// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{

    // Companies
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public class Company
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // Description (length: 300)
        public string Direccion { get; set; } // Direccion
        public bool Active { get; set; } // Active
        public System.DateTime DateCreation { get; set; } // DateCreation

        // Reverse navigation

        /// <summary>
        /// Child News (Many-to-Many) mapped by table [NewCompanies]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<News> News { get; set; } // Many to many mapping

        public Company()
        {
            News = new System.Collections.Generic.List<News>();
        }
    }

}
// </auto-generated>
